services:
  postgres_users:
    image: postgres:15
    environment:
      POSTGRES_USER: htrace
      POSTGRES_PASSWORD: htrace_secret
      POSTGRES_DB: users
    volumes:
      - pg_users_data:/var/lib/postgresql/data
    networks:
      - htrace

  postgres_threats:
    image: postgres:15
    environment:
      POSTGRES_USER: htrace
      POSTGRES_PASSWORD: htrace_secret
      POSTGRES_DB: threats
    volumes:
      - pg_threats_data:/var/lib/postgresql/data
    networks:
      - htrace

  elasticsearch:
    image: elasticsearch:8.11.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - htrace

  redis:
    image: redis:7
    networks:
      - htrace

  auth_service:
    build: ./backend/auth_service
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001
    networks:
      - htrace

  threat_intel_service:
    build: ./backend/threat_intel_service
    command: uvicorn app.main:app --host 0.0.0.0 --port 8002
    environment:
      DATABASE_URL: postgresql://htrace:htrace_secret@postgres_threats/threats
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - "8002:8002"
    depends_on:
      - postgres_threats
      - elasticsearch
    networks:
      - htrace

  source_connector_service:
    image: alpine
    command: tail -f /dev/null
    networks:
      - htrace


  api_gateway:
    build: ./backend/api_gateway
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      AUTH_SERVICE_URL: http://auth_service:8001
      THREAT_INTEL_SERVICE_URL: http://threat_intel_service:8002
      SECRET_KEY: change_me_to_a_random_string   # must match the auth service's key
    ports:
      - "8000:8000"
    depends_on:
      - auth_service
      - threat_intel_service
    networks:
      - htrace


  frontend:
    image: alpine
    command: tail -f /dev/null
    ports:
      - "3000:3000"
    networks:
      - htrace

networks:
  htrace:

volumes:
  pg_users_data:
  pg_threats_data:
  es_data:
